# Generated by Django 6.0.4 on 2026-04-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0002_alter_dataset_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('sql_generated', models.TextField(blank=True)),
                ('execution_time', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=False)),
                ('error_msg', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('cached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='dataset.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(1, 'Útil'), (-1, 'No útil')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='queries.queryhistory')),
            ],
        ),
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(default=list)),
                ('columns', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('chart_type', models.CharField(choices=[('bar', 'Barras'), ('line', 'Linea'), ('pie', 'Torta'), ('scatter', 'Dispersion'), ('table', 'Tabla')], default='table', max_length=10)),
                ('chart_config', models.JSONField(default=dict)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='queries.queryhistory')),
            ],
        ),
        migrations.AddIndex(
            model_name='queryhistory',
            index=models.Index(fields=['user', 'created_at'], name='queries_que_user_id_41fe64_idx'),
        ),
        migrations.AddIndex(
            model_name='queryhistory',
            index=models.Index(fields=['dataset', 'success'], name='queries_que_dataset_d47305_idx'),
        ),
        migrations.AddIndex(
            model_name='queryhistory',
            index=models.Index(fields=['user', 'success'], name='queries_que_user_id_e777d3_idx'),
        ),
    ]
