# Generated by Django 6.0.5 on 2026-07-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresult',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Barras'), ('line', 'Linea'), ('pie', 'Torta'), ('scatter', 'Dispersion'), ('table', 'Tabla'), ('forecast', 'Pronostico'), ('anomaly', 'Anomalias'), ('segment', 'Segmentacion'), ('drivers', 'Factores')], default='table', max_length=10),
        ),
    ]
