# Generated by Django 6.0.5 on 2026-07-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_alter_queryresult_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
