"""
Django settings for conversationalBI project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env(
    # Define el tipo de variable y su valor por defecto
    DEBUG=(bool, False)
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #! APPS
    "apps.users",
    "apps.dataset",
    "apps.queries",
    #! API REST
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASE_URL presente (Supabase pooler o Postgres local) → Postgres.
# Sin DATABASE_URL → SQLite de respaldo (solo para correr la suite de
# tests sin Postgres; el uso real siempre es Postgres).
#
# Guard de tests: bajo pytest la BD del .env NUNCA se usa (puede ser el
# Supabase de producción). La capa Postgres de datasets se ejercita solo
# con una URL explícita y local:
#   CBI_TEST_DATABASE_URL=postgres://...localhost... \
#   CBI_TEST_DATABASE_READER_URL=postgres://...localhost... pytest
# Sin esas vars, los tests requires_postgres se saltan (conftest.py).
import sys

_TESTING = "pytest" in sys.modules

# .strip() defensivo: un espacio/salto de línea al pegar la URL en un
# dashboard (Render, etc.) rompe psycopg2.connect() con "invalid dsn"
# (django-environ tolera esos caracteres, psycopg2 no).
if _TESTING:
    DATABASE_URL = env("CBI_TEST_DATABASE_URL", default="").strip()
    DATABASE_READER_URL = env("CBI_TEST_DATABASE_READER_URL", default="").strip()
else:
    DATABASE_URL = env("DATABASE_URL", default="").strip()
    DATABASE_READER_URL = env("DATABASE_READER_URL", default="").strip()
DATABASE_READER_ROLE = env("DATABASE_READER_ROLE", default="bi_reader")

if DATABASE_URL:
    DATABASES = {
        "default": {
            **env.db("DATABASE_URL"),
            "OPTIONS": {"options": "-c statement_timeout=30000"},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


#! SERIALIZADORES

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.users.authentication.SupabaseAuth",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "100/hour",
        "anon": "20/hour",
    },
}

AUTH_USER_MODEL = "users.User"


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}


#! LLM — cliente agnóstico: cualquier endpoint OpenAI-compatible
# (OpenCode Go, Groq, OpenRouter, Ollama). Se cambia por env vars.
LLM_API_KEY = env("LLM_API_KEY", default="")
LLM_BASE_URL = env("LLM_BASE_URL", default="https://opencode.ai/zen/go/v1")
LLM_SQL_MODEL = env("LLM_SQL_MODEL", default="kimi-k2.7-code")
LLM_ANSWER_MODEL = env("LLM_ANSWER_MODEL", default="mimo-v2.5")
LLM_TIMEOUT = env.int("LLM_TIMEOUT", default=60)


SUPABASE_URL = env("SUPABASE_URL", default="")
