# Generated by Django 6.0.4 on 2026-04-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='query_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='query_limit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
