# Generated by Django 6.0.5 on 2026-05-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_query_count_profile_query_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type_id',
        ),
    ]
